swagger: "2.0"
info:
  version: "1.0.0"
  title: Unified Network Slice Lifecycle Management API
paths:
  /NSSMF_NonRTRIC:
    post:
      summary: Create a new NSSMF-Non-RT RIC entry
      description: Creates a new entry for NSSMF-Non-RT RIC interface
      parameters:
        - name: nssmfNonRtricRequest
          in: body
          description: Request parameters for NSSMF-Non-RT RIC interface
          required: true
          schema:
            $ref: "#/definitions/NSSMFNonRTRICRequest"
      responses:
        200:
          description: Successful response

  /NSSMF_NonRTRIC/{id}:
    get:
      summary: Get an NSSMF-Non-RT RIC entry by ID
      description: Retrieves an existing NSSMF-Non-RT RIC entry by ID
      parameters:
        - name: id
          in: path
          description: The ID of the NSSMF-Non-RT RIC entry
          required: true
          type: string
      responses:
        200:
          description: Successful response

    put:
      summary: Update an NSSMF-Non-RT RIC entry by ID
      description: Updates an existing NSSMF-Non-RT RIC entry by ID
      parameters:
        - name: id
          in: path
          description: The ID of the NSSMF-Non-RT RIC entry
          required: true
          type: string
        - name: nssmfNonRtricRequest
          in: body
          description: Updated request parameters for NSSMF-Non-RT RIC interface
          required: true
          schema:
            $ref: "#/definitions/NSSMFNonRTRICRequest"
      responses:
        200:
          description: Successful response

    delete:
      summary: Delete an NSSMF-Non-RT RIC entry by ID
      description: Deletes an existing NSSMF-Non-RT RIC entry by ID
      parameters:
        - name: id
          in: path
          description: The ID of the NSSMF-Non-RT RIC entry
          required: true
          type: string
      responses:
        200:
          description: Successful response

  /NFVO_NonRTRIC:
    post:
      summary: Create a new NFVO-Non-RT RIC entry
      description: Creates a new entry for NFVO-Non-RT RIC interface
      parameters:
        - name: nfvoNonRtricRequest
          in: body
          description: Request parameters for NFVO-Non-RT RIC interface
          required: true
          schema:
            $ref: "#/definitions/NFVONonRTRICRequest"
      responses:
        200:
          description: Successful response

  /NFVO_NonRTRIC/{id}:
    get:
      summary: Get an NFVO-Non-RT RIC entry by ID
      description: Retrieves an existing NFVO-Non-RT RIC entry by ID
      parameters:
        - name: id
          in: path
          description: The ID of the NFVO-Non-RT RIC entry
          required: true
          type: string
      responses:
        200:
          description: Successful response

    put:
      summary: Update an NFVO-Non-RT RIC entry by ID
      description: Updates an existing NFVO-Non-RT RIC entry by ID
      parameters:
        - name: id
          in: path
          description: The ID of the NFVO-Non-RT RIC entry
          required: true
          type: string
        - name: nfvoNonRtricRequest
          in: body
          description: Updated request parameters for NFVO-Non-RT RIC interface
          required: true
          schema:
            $ref: "#/definitions/NFVONonRTRICRequest"
      responses:
        200:
          description: Successful response

    delete:
      summary: Delete an NFVO-Non-RT RIC entry by ID
      description: Deletes an existing NFVO-Non-RT RIC entry by ID
      parameters:
        - name: id
          in: path
          description: The ID of the NFVO-Non-RT RIC entry
          required: true
          type: string
      responses:
        200:
          description: Successful response

  /NSSMF_Termination:
    post:
      summary: Message exchange between NSSMF and Non-RT RIC
      description: Facilitates message exchange between NSSMF and Non-RT RIC via the NSSMF_NonRTRIC interface
      parameters:
        - name: nssmfTerminationRequest
          in: body
          description: Request parameters for NSSMF Termination
          required: true
          schema:
            $ref: "#/definitions/NSSMFTerminationRequest"
      responses:
        200:
          description: Successful response

  /NFVO_Termination:
    post:
      summary: Message exchange between NFVO and Non-RT RIC
      description: Facilitates message exchange between NFVO and Non-RT RIC via the NFVO_NonRTRIC interface
      parameters:
        - name: nfvoTerminationRequest
          in: body
          description: Request parameters for NFVO Termination
          required: true
          schema:
            $ref: "#/definitions/NFVOTerminationRequest"
      responses:
        200:
          description: Successful response

definitions:
  NSSMFNonRTRICRequest:
    type: object
    properties:
      sliceId:
        type: string
        description: The ID of the network slice
      serviceType:
        type: string
        description: The type of service requested for the network slice
      qosProfile:
        type: object
        description: The quality of service profile for the network slice
        properties:
          latency:
            type: integer
            description: The maximum latency allowed for the network slice
          throughput:
            type: integer
            description: The minimum throughput required for the network slice
          reliability:
            type: string
            description: The desired reliability level for the network slice
      securityLevel:
        type: string
        description: The desired security level for the network slice

  NFVONonRTRICRequest:
    type: object
    properties:
      sliceId:
        type: string
        description: The ID of the network slice
      nfvoId:
        type: string
        description: The ID of the NFVO

  NSSMFTerminationRequest:
    type: object
    properties:
      sliceId:
        type: string
        description: The ID of the network slice
      terminationType:
        type: string
        description: The type of termination request

  NFVOTerminationRequest:
    type: object
    properties:
      sliceId:
        type: string
        description: The ID of the network slice
      terminationType:
        type: string
        description: The type of termination request
